version: '2'
services:
    projeto_jhipster-mongodb:
        container_name: projeto_jhipster-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/projeto_jhipster/mongodb/:/data/db/
